export const PET_CREATE_REQUEST = 'PET_CREATE_REQUEST';
export const PET_CREATE_SUCCESS = 'PET_CREATE_SUCCESS';
export const PET_CREATE_FAIL = 'PET_CREATE_FAIL';
export const PET_CREATE_RESET = 'PET_CREATE_RESET';


export const PET_DELETE_REQUEST = 'PET_DELETE_REQUEST';
export const PET_DELETE_SUCCESS = 'PET_DELETE_SUCCESS';
export const PET_DELETE_FAIL = 'PET_DELETE_FAIL';
export const PET_DELETE_RESET = 'PET_DELETE_RESET';


export const PET_UPDATE_REQUEST = 'USER_DETAILS_REQUEST';
export const PET_UPDATE_SUCCESS = 'USER_DETAILS_SUCCESS';
export const PET_UPDATE_FAIL = 'USER_DETAILS_FAIL';