export const WALK_CREATE_REQUEST = 'WALK_CREATE_REQUEST';
export const WALK_CREATE_SUCCESS = 'WALK_CREATE_SUCCESS';
export const WALK_CREATE_FAIL = 'WALK_CREATE_FAIL';
export const WALK_CREATE_RESET = 'WALK_CREATE_RESET';

export const WALK_GET_BY_WALKER_REQUEST = 'WALK_GET_BY_WALKER_REQUEST';
export const WALK_GET_BY_WALKER_SUCCESS = 'WALK_GET_BY_WALKER_SUCCESS';
export const WALK_GET_BY_WALKER_FAIL = 'WALK_GET_BY_WALKER_FAIL';
export const WALK_GET_BY_WALKER_RESET = 'WALK_GET_BY_WALKER_RESET';

export const WALK_DELETE_REQUEST = 'WALK_DELETE_REQUEST';
export const WALK_DELETE_SUCCESS = 'WALK_DELETE_SUCCESS';
export const WALK_DELETE_FAIL = 'WALK_DELETE_FAIL';
export const WALK_DELETE_RESET = 'WALK_DELETE_RESET';

export const WALK_UPDATE_REQUEST = 'WALK_UPDATE_REQUEST';
export const WALK_UPDATE_SUCCESS = 'WALK_UPDATE_SUCCESS';
export const WALK_UPDATE_FAIL = 'WALK_UPDATE_FAIL';
export const WALK_UPDATE_RESET = 'WALK_UPDATE_RESET';